name: ci

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main, master ]
  workflow_call:

jobs:
  lint:
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        platform: [ ubuntu-latest ]
    name: lint check
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest

  test:
    needs: [ lint ]
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        platform: [ ubuntu-latest ]  # [ubuntu-latest, macos-latest, windows-latest]
    name: test go app
    runs-on: ${{ matrix.platform }}
    steps:
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: test go app
        run: go test -v ./...

  build:
    needs: [ lint ]
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        platform: [ ubuntu-latest ]
    name: build go app
    runs-on: ${{ matrix.platform }}
    steps:
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: checkout repository
      uses: actions/checkout@v3
    - name: build artifacts
      run: |
        go build -o app ./...
